-- Seed VertKlean result cards as published CMS entries.
-- Idempotent. Apply through a service-role connection.

insert into public.content_entries (type, slug, title, status, locale, payload, seo)
values
  ('proof_card', 'ddc-rust-test', 'Rust-and-scale removal', 'published', 'en', '{"eyebrow":"HVAC & Water · Result","kind":"hvac","chips":["VertKlean HCR"],"source":"Source: field record","publication_scope":"Published result summary","image":"img/proof/cases/ddc-rust.webp?v=20260617b","image_alt":"Metal surface after VertKlean HCR rust-and-scale removal","result":"VertKlean HCR cut through heavy rust and mineral scale, revealing a dramatically cleaner metal surface.","narrative":"Heavy rust and mineral scale covered the metal. HCR used a controlled hydrogen-ion reaction to release carbonate and oxide deposits; the field record shows a visibly cleaner surface after descaling.","sort_order":1,"image_w":1200,"image_h":579}'::jsonb, '{}'::jsonb),
  ('proof_card', 'brewery-cip-trials', 'CR + HCR brewery CIP results', 'published', 'en', '{"eyebrow":"Food & Beverage · CIP result","kind":"food","chips":["VertKlean CR + HCR"],"source":"Source: laboratory and field records","publication_scope":"Published result summary","image":"img/proof/cases/brewery.webp?v=20260617b","image_alt":"Brewery tank and heat exchanger cleaned with VertKlean CR and HCR","result":"VertKlean CR and HCR replaced caustic and mineral acid in brewery CIP while removing organics, beer stone, rust, and scale across process equipment.","narrative":"Organic soil and mineral beer stone required different mechanisms. CR wet and lifted organic load; HCR reacted with carbonate scale and rust, giving crews one two-step tank and heat-exchanger cycle.","sort_order":2,"image_w":1200,"image_h":900}'::jsonb, '{}'::jsonb),
  ('proof_card', 'distribution-center-assessment', 'Distribution-center equipment degreasing', 'published', 'en', '{"eyebrow":"Distribution · Assessment","kind":"distribution","chips":["VertKlean CR HD","Customer assessment"],"source":"Source: customer assessment","publication_scope":"Published result summary","image":"img/industries/distribution-cold-storage/g1.webp","image_alt":"Material-handling equipment during a VertKlean CR HD assessment","result":"The distribution-center assessment matched VertKlean CR HD to heavy-equipment grease and material-handling soils.","narrative":"The assessment recorded equipment soils, surfaces, current process, and cleaning endpoint. CR HD brings high-pH wetting and soil lift to the planned benchmark, giving the crew a defined side-by-side comparison.","sort_order":3,"image_w":1600,"image_h":1200}'::jsonb, '{}'::jsonb),
  ('proof_card', 'yellowfin-torque-wash', 'Vessel wash and finish', 'published', 'en', '{"eyebrow":"Marine · Result","kind":"marine","chips":["VertKlean Torque"],"source":"Source: field record","publication_scope":"Published result summary","image":"img/proof/cases/marine.webp?v=20260617b","image_alt":"Marine vessel after VertKlean Torque wash","result":"VertKlean Torque cleaned and finished a working vessel in one streamlined wash, leaving a polished marine surface.","narrative":"Road film and marine soil dulled the working vessel. Torque surfactants released the film while finish-care components remained after rinse, producing a clean, glossy surface in one wash.","sort_order":4,"image_w":1175,"image_h":1125}'::jsonb, '{}'::jsonb),
  ('proof_card', 'uf-shands-drone-wash', 'Drone-applied exterior cleaning', 'published', 'en', '{"eyebrow":"Drone cleaning · Result","kind":"facility","chips":["VertKlean MultiWash"],"source":"Source: field record","publication_scope":"Published result summary","image":"img/proof/cases/drone-before.webp?v=20260617b","image_alt":"Facility exterior before drone-applied MultiWash cleaning","result":"VertKlean MultiWash removed exterior buildup through drone-applied cleaning, reaching a large facility surface with speed and visible impact.","narrative":"Exterior buildup covered a large elevated surface. MultiWash wet and lifted mixed soil through drone application; before-and-after frames show a visibly cleaner facade without changing access methods.","sort_order":5,"image_w":1200,"image_h":803,"image_after":"img/proof/cases/drone-after.webp?v=20260617b","image_after_alt":"Facility exterior after drone-applied MultiWash cleaning","image_after_w":1200,"image_after_h":1029}'::jsonb, '{}'::jsonb),
  ('proof_card', 'neatfreaks-hood-degrease', 'Restaurant hood and floor degreasing', 'published', 'en', '{"eyebrow":"Food service · Result","kind":"food","chips":["VertKlean CR + CR HD"],"source":"Source: field record","publication_scope":"Published result summary","image":"img/proof/cases/hood-before.webp?v=20260617b","image_alt":"Restaurant hood filter before VertKlean degreasing","result":"VertKlean CR and CR HD stripped heavy grease from restaurant hood filters and floors, delivering a visibly cleaner food-service workspace.","narrative":"Heavy grease loaded hood filters and floors. CR and CR HD used high-pH wetting, sequestration, and soil lift to release the soils; before-and-after images show visibly cleaner food-service surfaces.","sort_order":6,"image_w":520,"image_h":650,"image_after":"img/proof/cases/hood-after.webp?v=20260617b","image_after_alt":"Restaurant hood filter after VertKlean degreasing","image_after_w":520,"image_after_h":650}'::jsonb, '{}'::jsonb),
  ('proof_card', 'fire-pump-descaler', 'Fire-system component descaling', 'published', 'en', '{"eyebrow":"Fire systems · Result","kind":"facility","chips":["VertKlean Descaler"],"source":"Source: field record","publication_scope":"Published result summary","image":"img/proof/cases/fire-pump.webp?v=20260617b","image_alt":"Fire-system component after VertKlean descaling","result":"VertKlean Descaler cleared mineral buildup from a fire-system component without the handling burden of conventional hydrochloric acid.","narrative":"Mineral buildup covered the component. Descaler combined wetting with a controlled mineral reaction to release the deposit; the service record shows a visibly cleaner surface after the cycle.","sort_order":7,"image_w":681,"image_h":681}'::jsonb, '{}'::jsonb),
  ('proof_card', 'residential-ac-coil', 'Residential AC coil restoration', 'published', 'en', '{"eyebrow":"Residential HVAC · Result","kind":"hvac","chips":["VertKlean Descaler"],"source":"Source: field record","publication_scope":"Published result summary","image":"img/proof/cases/ac-coil.webp?v=20260617b","image_alt":"Residential AC coil after VertKlean cleaning","result":"VertKlean Descaler removed stubborn buildup from a residential AC coil, restoring a visibly cleaner heat-transfer surface.","narrative":"Buildup loaded the coil and heat-transfer surface. Descaler used wetting and controlled mineral removal to reach the fin pack; the service record shows a visibly cleaner coil after rinsing.","sort_order":8,"image_w":839,"image_h":471}'::jsonb, '{}'::jsonb),
  ('proof_card', 'airboat-alumibrite', 'Marine aluminum restoration', 'published', 'en', '{"eyebrow":"Marine · Result","kind":"marine","chips":["AlumiBrite + Torque"],"source":"Source: field record","publication_scope":"Published result summary","image":"img/proof/cases/airboat-before.webp?v=20260617b","image_alt":"Aluminum vessel before the VertKlean restoration","result":"AlumiBrite lifted oxidation and weathering from the aluminum while Torque delivered a clean, finished vessel surface.","narrative":"Oxidation and weathering left the aluminum dull. AlumiBrite used wetting and controlled oxide removal; Torque lifted remaining film and left a polished finish, combining restoration and finish care.","sort_order":9,"image_w":682,"image_h":619,"image_after":"img/proof/cases/airboat-after.webp?v=20260617b","image_after_alt":"Brighter aluminum vessel after the VertKlean restoration","image_after_w":817,"image_after_h":857}'::jsonb, '{}'::jsonb),
  ('proof_card', 'brevard-farm-hvac', 'HVAC rust and scale restoration', 'published', 'en', '{"eyebrow":"HVAC & Water · Result","kind":"hvac","chips":["VertKlean HCR"],"source":"Source: field record","publication_scope":"Published result summary","image":"img/proof/cases/farm-rust-before.webp?v=20260617b","image_alt":"HVAC metal and diamond plate before HCR cleaning","result":"VertKlean HCR removed stubborn rust and mineral scale from HVAC metal and diamond plate, restoring visibly cleaner surfaces without conventional acid.","narrative":"Rust and mineral scale covered HVAC metal and diamond plate. HCR used controlled mineral-removal chemistry to release the deposits; the recorded surfaces finished visibly cleaner with one descaling method.","sort_order":10,"image_w":1057,"image_h":844,"image_after":"img/proof/cases/farm-rust-after.webp?v=20260617b","image_after_alt":"HVAC metal and diamond plate after HCR cleaning","image_after_w":740,"image_after_h":967}'::jsonb, '{}'::jsonb),
  ('proof_card', 'property-grout-moss', 'Property-surface restoration', 'published', 'en', '{"eyebrow":"Property · Result","kind":"facility","chips":["VertKlean CR + LAM3"],"source":"Source: field record","publication_scope":"Published result summary","image":"img/proof/cases/grout-before.webp?v=20260617b","image_alt":"Property surface before VertKlean cleaning","result":"VertKlean CR and LAM3 lifted embedded exterior soil, biological buildup, and grout staining for a dramatic property-cleaning result.","narrative":"Embedded soil, biological buildup, and grout staining marked the property surfaces. CR lifted soil while LAM3 supported longer-dwell exterior cleaning; the sequence shows visibly cleaner hardscape and grout.","sort_order":11,"image_w":934,"image_h":700,"image_after":"img/proof/cases/grout-after.webp?v=20260617b","image_after_alt":"Property surface after VertKlean cleaning","image_after_w":850,"image_after_h":882}'::jsonb, '{}'::jsonb),
  ('proof_card', 'commercial-kitchen-crhd', 'Commercial-kitchen grease removal', 'published', 'en', '{"eyebrow":"Food service · Result","kind":"food","chips":["VertKlean CR HD"],"source":"Source: field record","publication_scope":"Published result summary","image":"img/proof/cases/kitchen-before.webp?v=20260617b","image_alt":"Commercial-kitchen surface before CR HD cleaning","result":"VertKlean CR HD broke through baked-on commercial-kitchen grease and restored a visibly cleaner working surface.","narrative":"Baked-on grease loaded the working surface. CR HD used high-pH wetting, sequestration, and soil lift to break it free; the before-and-after sequence shows a visibly cleaner kitchen area.","sort_order":12,"image_w":917,"image_h":852,"image_after":"img/proof/cases/kitchen-after.webp?v=20260617b","image_after_alt":"Commercial-kitchen surface after CR HD cleaning","image_after_w":1200,"image_after_h":900}'::jsonb, '{}'::jsonb),
  ('proof_card', 'cr-caustic-replacement', 'VertKlean CIP CR caustic-replacement record', 'published', 'en', '{"eyebrow":"VertKlean CIP CR · Equivalency","kind":"food","chips":["VertKlean CIP CR","Caustic replacement"],"source":"Source: product record","publication_scope":"Published product record","image":"img/products/cip-cr-studio.webp","image_alt":"VertKlean CIP CR product","result":"VertKlean CIP CR has an exact-product caustic-replacement path for the current concentration and job.","narrative":"Share the current caustic concentration, cycle conditions, and completion target; MASEST returns a product-fit recommendation and starting application scope.","sort_order":13,"image_w":900,"image_h":1200}'::jsonb, '{}'::jsonb),
  ('proof_card', 'cr2-caustic-replacement', 'VertKlean HVAC CR 60% caustic-replacement record', 'published', 'en', '{"eyebrow":"VertKlean HVAC CR · Equivalency","kind":"hvac","chips":["VertKlean HVAC CR","60% sodium hydroxide replacement"],"source":"Source: product record","publication_scope":"Published product record","image":"img/products/hvac-cr-studio.webp","image_alt":"VertKlean HVAC CR product","result":"VertKlean HVAC CR is recorded as a direct replacement for 60% sodium hydroxide.","narrative":"Share the current concentration, asset, soil, and operating conditions; MASEST returns application guidance mapped to the HVAC job.","sort_order":14,"image_w":900,"image_h":1200}'::jsonb, '{}'::jsonb),
  ('proof_card', 'watersafe60-nsf60', 'WaterSafe60 NSF/ANSI/CAN 60 record', 'published', 'en', '{"eyebrow":"WaterSafe60 · Certification","kind":"hvac","chips":["WaterSafe60","NSF/ANSI/CAN 60"],"source":"Source: product record","publication_scope":"Published product record","image":"img/products/watersafe60-studio.webp","image_alt":"WaterSafe60 product","result":"WaterSafe60 is NSF/ANSI/CAN 60 certified for lowering potable-water pH, well rehabilitation, corrosion and scale control, and pipe cleaning.","narrative":"Share system use, volume, materials, and water data; MASEST returns the listed-use record and a system-specific starting scope.","sort_order":15,"image_w":900,"image_h":1200}'::jsonb, '{}'::jsonb)
on conflict (type, slug, locale) do update
  set title = excluded.title, status = excluded.status, payload = excluded.payload,
      seo = excluded.seo, published_at = coalesce(public.content_entries.published_at, now()), updated_at = now();

update public.content_entries set published_at = coalesce(published_at, now())
  where type = 'proof_card' and status = 'published';
