-- MASEST products - generated by tools/build-catalog.mjs from data/catalog.seed.json. DO NOT edit by hand.
insert into public.products (sku, name, group_key, hmis, mode, hazmat, taxable, price, sort)
values
('cr','VertKleen CR','cip_brewery','0-0-0','buy',false,true,null,1),
('cr2','VertKleen CR2','water','0-0-0','buy',false,true,null,2),
('hcr','VertKleen HCR','descale','0-0-0','buy',false,true,null,3),
('hcr-t16','VertKleen HCR - 16+ Tote Program','descale','0-0-0','buy',false,true,null,4),
('descaler','VertKleen Descaler','hvac_coils','0-0-0','buy',false,true,null,5),
('cr-hd','VertKleen CRHD','degrease','0-0-0','buy',false,true,null,6),
('cr-hd-low-foam','VertKleen CRHD Low Foam','degrease','0-0-0','buy',false,true,null,7),
('neutral','VertKleen Neutral','degrease','0-0-0','buy',false,true,null,8),
('multiwash','VertKleen MultiWash (Fortis)','softwash_exterior','0-0-0','buy',false,true,null,9),
('lam3','VertKleen Lam3','softwash_exterior','0-0-0','buy',false,true,null,10),
('purgo','VertKleen Purgo','water','0-0-0','buy',false,true,null,11),
('alumibrite','VertKleen AlumiBrite','marine','0-0-0','buy',false,true,null,12),
('torque','VertKleen Torque','marine','0-0-0','buy',false,true,null,13),
('sar','VertKleen SAR','specialty','0-0-0','buy',false,true,null,14),
('watersafe60','Watersafe60','water','0-0-0','buy',false,true,null,15)
on conflict (sku) do update set
  name = excluded.name,
  group_key = excluded.group_key,
  hmis = excluded.hmis,
  mode = excluded.mode,
  hazmat = excluded.hazmat,
  taxable = excluded.taxable,
  price = excluded.price,
  sort = excluded.sort;

delete from public.products where sku not in ('cr','cr2','hcr','hcr-t16','descaler','cr-hd','cr-hd-low-foam','neutral','multiwash','lam3','purgo','alumibrite','torque','sar','watersafe60');
