-- Seed the 11 industry sector row-cards as published industry_sector CMS entries,
-- extracted verbatim from industries.html .industry-grid (tools-side parser). Mirrors the
-- hardcoded fallback so the admin CMS owns them and Supabase-backed builds keep emitting
-- industry-sectors.json. sort_order preserves the curated DOM order; image_w/image_h reserve
-- layout (CLS); the "View fit" target is derived from slug at render time. Idempotent.
-- Apply via the pooled service-role connection.

insert into public.content_entries (type, slug, title, status, locale, payload, seo)
values
  ('industry_sector', 'oil-gas', 'Oil & Gas', 'published', 'en', '{"icon":"ph-gas-can","summary":"Descale, derust, and degrease rigs, terminals, and pipelines without acid fumes, a solvent storage cabinet, or hazmat freight.","image":"img/proof/cases/fire-pump.webp","image_alt":"Industrial pump equipment cleaned with VertKleen chemistry","image_w":168,"image_h":104,"href":"proof","image_label":"View Oil and Gas proof photo","sort_order":1}'::jsonb, '{}'::jsonb),
  ('industry_sector', 'marine', 'Marine', 'published', 'en', '{"icon":"ph-anchor","summary":"Wash, brighten, and degrease vessels in confined air, on soft metal, against salt and corrosion — where the wrong chemical does damage of its own.","image":"img/proof/cases/marine.webp","image_alt":"Yellowfin vessel washed with VertKleen Torque","image_w":168,"image_h":104,"href":"proof","image_label":"View Marine proof photo","sort_order":2}'::jsonb, '{}'::jsonb),
  ('industry_sector', 'manufacturing', 'Manufacturing', 'published', 'en', '{"icon":"ph-factory","summary":"Heavy-duty cleaning for extrusion, processing, warehousing, and plant maintenance — get the line running again with less HazCom paperwork to answer for.","image":"img/proof/cases/farm-rust.webp","image_alt":"Industrial steel surface derusted with VertKleen HCR","image_w":168,"image_h":104,"href":"proof","image_label":"View Manufacturing proof photo","sort_order":3}'::jsonb, '{}'::jsonb),
  ('industry_sector', 'distribution-cold-storage', 'Distribution / Cold Storage', 'published', 'en', '{"icon":"ph-warehouse","summary":"Refrigerated bays, ammonia coils, forklifts, kitchen grease, and drain lines in perishable distribution centers — backed by documented results from Walmart DSC.","image":"img/proof/cases/walmart-dc-crhd.webp","image_alt":"Walmart distribution center degreasing proof for VertKleen CRHD","image_w":168,"image_h":104,"href":"industries/distribution-cold-storage","image_label":"View Distribution and Cold Storage fit","sort_order":4}'::jsonb, '{}'::jsonb),
  ('industry_sector', 'food-beverage', 'Food & Beverage', 'published', 'en', '{"icon":"ph-beer-bottle","summary":"CIP/SIP, hoods, floors, drains, and tanks — with CR and HCR proven on brewery and distillery jobs.","image":"img/proof/cases/brewery.webp","image_alt":"Brewery tank cleaned with VertKleen CR and HCR","image_w":168,"image_h":104,"href":"proof#brewery-cip-trials","image_label":"View Food and Beverage proof photo","sort_order":5}'::jsonb, '{}'::jsonb),
  ('industry_sector', 'healthcare', 'Healthcare', 'published', 'en', '{"icon":"ph-hospital","summary":"Clean, passivate, and service water systems with patients still in the building — no fume events, no evacuations, no shutting a wing to do maintenance.","image":"img/proof/cases/ac-coil.webp","image_alt":"Occupied-facility HVAC coil cleaned with VertKleen","image_w":168,"image_h":104,"href":"proof","image_label":"View Healthcare proof photo","sort_order":6}'::jsonb, '{}'::jsonb),
  ('industry_sector', 'construction', 'Construction', 'published', 'en', '{"icon":"ph-crane","summary":"Concrete cleaning, equipment upkeep, rust removal, and site cleanup on active jobs — easier to store on site, safer to have around the crew.","image":"img/proof/cases/grout-moss.webp","image_alt":"Exterior concrete cleaned with VertKleen CR","image_w":168,"image_h":104,"href":"proof","image_label":"View Construction proof photo","sort_order":7}'::jsonb, '{}'::jsonb),
  ('industry_sector', 'military-government', 'Military / Government', 'published', 'en', '{"icon":"ph-seal-check","summary":"MASEST sells through SAM.gov under CAGE 0B2Q3 and NAICS 424690, ready for federal, state, local, and public-facility buyers.","image":"img/proof/cases/ddc-rust.webp","image_alt":"Rust removed from defense-contractor equipment with VertKleen HCR","image_w":168,"image_h":104,"href":"proof","image_label":"View Military and Government proof photo","sort_order":8}'::jsonb, '{}'::jsonb),
  ('industry_sector', 'education', 'Education', 'published', 'en', '{"icon":"ph-graduation-cap","summary":"K-12 and university facilities can clean and treat systems with students and staff still on campus. Brevard County Schools is the reference account.","image":"img/proof/product-line-2026-enhanced.webp","image_alt":"VertKleen chemistry line for campus facility programs","image_w":168,"image_h":104,"href":"proof","image_label":"View Education proof photo","sort_order":9}'::jsonb, '{}'::jsonb),
  ('industry_sector', 'hvac-water', 'HVAC / Water Treatment', 'published', 'en', '{"icon":"ph-wind","summary":"Cooling tower programs built on WaterSafe60 inhibitor, Purgo minimum-risk antimicrobial, HCR passivation, CR pH control, and the ASHRAE 188 paperwork to back them.","image":"img/proof/cases/ac-coil.webp","image_alt":"HVAC coil cleaned with VertKleen","image_w":168,"image_h":104,"href":"proof","image_label":"View HVAC and Water Treatment proof photo","sort_order":10}'::jsonb, '{}'::jsonb),
  ('industry_sector', 'plumbing', 'Plumbing', 'published', 'en', '{"icon":"ph-wrench","summary":"Water lines, fixtures, water heaters, and drains cleared of scale and calcium without handling hydrochloric acid — and checked against your metals before occupied-building work.","sort_order":11}'::jsonb, '{}'::jsonb)
on conflict (type, slug, locale) do update
  set title = excluded.title, status = excluded.status, payload = excluded.payload,
      seo = excluded.seo, published_at = coalesce(public.content_entries.published_at, now()), updated_at = now();

update public.content_entries set published_at = coalesce(published_at, now())
  where type = 'industry_sector' and status = 'published';
