-- Seed the 11 industry sector row-cards as published industry_sector CMS entries,
-- extracted verbatim from industries.html .industry-grid (tools-side parser). Mirrors the
-- hardcoded fallback so the admin CMS owns them and Supabase-backed builds keep emitting
-- industry-sectors.json. sort_order preserves the curated DOM order; image_w/image_h reserve
-- layout (CLS); the "View fit" target is derived from slug at render time. Idempotent.
-- Apply via the pooled service-role connection.

insert into public.content_entries (type, slug, title, status, locale, payload, seo)
values
  ('industry_sector', 'oil-gas', 'Oil & Gas', 'published', 'en', '{"icon":"ph-gas-can","summary":"Contained descaling and degreasing for de-inventoried rigs, terminals, process skids, exchangers, valves, and plant-support assets.","image":"img/industries/samples/oil-gas.webp","image_alt":"Oil and gas worker cleaning an isolated valve manifold and heat exchanger","image_w":168,"image_h":104,"href":"industries/oil-gas","image_label":"View Oil, Gas and Process Plants industry page","sort_order":1}'::jsonb, '{}'::jsonb),
  ('industry_sector', 'marine', 'Marine', 'published', 'en', '{"icon":"ph-anchor","summary":"Vessel wash, brightening, and degreasing scoped by substrate, coatings, containment, ventilation, and marina discharge rules.","image":"img/industries/samples/marine.webp","image_alt":"Boatyard worker cleaning a yacht hull while the vessel is in a lift","image_w":168,"image_h":104,"href":"industries/marine","image_label":"View Marine industry page","sort_order":2}'::jsonb, '{}'::jsonb),
  ('industry_sector', 'manufacturing', 'Manufacturing', 'published', 'en', '{"icon":"ph-factory","summary":"Heavy-duty cleaning for extrusion, processing, warehousing, and plant maintenance — with an SDS-led review package and controlled trial.","image":"img/industries/samples/manufacturing.webp","image_alt":"Manufacturing worker degreasing heavy production machinery","image_w":168,"image_h":104,"href":"industries/manufacturing","image_label":"View Manufacturing industry page","sort_order":3}'::jsonb, '{}'::jsonb),
  ('industry_sector', 'distribution-cold-storage', 'Distribution / Cold Storage', 'published', 'en', '{"icon":"ph-warehouse","summary":"Refrigerated bays, isolated refrigeration components, forklifts, kitchen grease, and drain lines — scoped through a cold-storage walkdown and controlled trial.","image":"img/industries/samples/distribution-cold-storage.webp","image_alt":"Cold-storage worker cleaning a refrigerated warehouse floor near a forklift","image_w":168,"image_h":104,"href":"industries/distribution-cold-storage","image_label":"View Distribution and Cold Storage industry page","sort_order":4}'::jsonb, '{}'::jsonb),
  ('industry_sector', 'food-beverage', 'Food & Beverage', 'published', 'en', '{"icon":"ph-beer-bottle","summary":"CIP/SIP, hoods, floors, drains, and tanks — with CR and HCR documented in MASEST trial notes and lab data available for review.","image":"img/industries/samples/food-beverage.webp","image_alt":"Food-processing technician operating a clean-in-place skid beside stainless tanks","image_w":168,"image_h":104,"href":"industries/food-beverage","image_label":"View Food and Beverage industry page","sort_order":5}'::jsonb, '{}'::jsonb),
  ('industry_sector', 'healthcare', 'Healthcare', 'published', 'en', '{"icon":"ph-hospital","summary":"Clean, passivate, and service water systems under facility infection-control, ventilation, isolation, and shutdown approval.","image":"img/industries/samples/healthcare.webp","image_alt":"Healthcare facilities technician descaling a plate heat exchanger in a mechanical room","image_w":168,"image_h":104,"href":"industries/healthcare","image_label":"View Healthcare industry page","sort_order":6}'::jsonb, '{}'::jsonb),
  ('industry_sector', 'construction', 'Construction', 'published', 'en', '{"icon":"ph-crane","summary":"Concrete cleaning, equipment upkeep, rust removal, and site cleanup with exact-SKU hazard review, containment, and wastewater routing.","image":"img/industries/samples/construction.webp","image_alt":"Workers cleaning concrete pump equipment and a commercial job-site slab","image_w":168,"image_h":104,"href":"industries/construction","image_label":"View Construction industry page","sort_order":7}'::jsonb, '{}'::jsonb),
  ('industry_sector', 'military-government', 'Military / Government', 'published', 'en', '{"icon":"ph-seal-check","summary":"Public-sector bid support with registration, CAGE and NAICS records, solicitation fit, country of origin, and current product documents verified during review.","image":"img/industries/samples/military-government.webp","image_alt":"Public-sector fleet worker washing a utility truck in a maintenance bay","image_w":168,"image_h":104,"href":"industries/military-government","image_label":"View Military and Government industry page","sort_order":8}'::jsonb, '{}'::jsonb),
  ('industry_sector', 'education', 'Education', 'published', 'en', '{"icon":"ph-graduation-cap","summary":"Campus mechanical, kitchen, restroom, gym, and exterior cleaning within district chemical review and occupied-space controls.","image":"img/industries/samples/education.webp","image_alt":"Campus facilities worker cleaning stained exterior steps and walkway","image_w":168,"image_h":104,"href":"industries/education","image_label":"View Education Facilities industry page","sort_order":9}'::jsonb, '{}'::jsonb),
  ('industry_sector', 'hvac-water', 'HVAC / Water Treatment', 'published', 'en', '{"icon":"ph-wind","summary":"Cooling-tower chemistry scoped inside the facility water-management plan, with current product documents, monitoring duties, and site approval kept separate.","image":"img/industries/samples/hvac-water.webp","image_alt":"HVAC technician servicing cooling-tower and heat-exchanger water equipment","image_w":168,"image_h":104,"href":"industries/hvac-water","image_label":"View HVAC and Water Treatment industry page","sort_order":10}'::jsonb, '{}'::jsonb),
  ('industry_sector', 'plumbing', 'Plumbing', 'published', 'en', '{"icon":"ph-wrench","summary":"Scale and calcium work on isolated water heaters, fixtures, and lines after metallurgy, ventilation, circulation, discharge, and reopening review.","image":"img/industries/samples/plumbing.webp","image_alt":"Plumber circulating descaling solution through tankless water heaters","image_w":168,"image_h":104,"href":"industries/plumbing","image_label":"View Plumbing industry page","sort_order":11}'::jsonb, '{}'::jsonb)
on conflict (type, slug, locale) do update
  set title = excluded.title, status = excluded.status, payload = excluded.payload,
      seo = excluded.seo, published_at = coalesce(public.content_entries.published_at, now()), updated_at = now();

update public.content_entries set published_at = coalesce(published_at, now())
  where type = 'industry_sector' and status = 'published';
