-- MASEST products - generated by tools/build-catalog.mjs from data/catalog.seed.json. DO NOT edit by hand.
insert into public.products (sku, name, group_key, hmis, mode, hazmat, taxable, price, sort)
values
('cr','VertKlean CIP CR','cip_brewery','0-0-0','buy',false,true,null,1),
('cr2','VertKlean HVAC CR','water','0-0-0','buy',false,true,null,2),
('hcr','VertKlean CIP HCR','descale','0-0-0','buy',false,true,null,3),
('hcr-t16','VertKlean HVAC HCR','descale','0-0-0','buy',false,true,null,4),
('descaler','VertKlean Descaler','hvac_coils','0-0-0','buy',false,true,null,5),
('cr-hd','VertKlean CRHD','degrease','0-0-0','buy',false,true,null,6),
('cr-hd-low-foam','VertKlean CRHD Low Foam','degrease','0-0-0','buy',false,true,null,7),
('neutral','VertKlean Neutral','degrease','0-0-0','buy',false,true,null,8),
('multiwash','VertKlean MultiWash','softwash_exterior','0-0-0','buy',false,true,null,9),
('lam3','VertKlean Lam3','softwash_exterior','0-0-0','buy',false,true,null,10),
('purgo','VertKlean Purgo','water','0-0-0','buy',false,true,null,11),
('alumibrite','VertKlean AlumiBrite','marine','0-0-0','buy',false,true,null,12),
('torque','VertKlean Torque','marine','0-0-0','buy',false,true,null,13),
('sar','VertKlean SAR','specialty','0-0-0','buy',false,true,null,14),
('watersafe60','Watersafe60','water','0-0-0','buy',false,true,null,15)
on conflict (sku) do update set
  name = excluded.name,
  group_key = excluded.group_key,
  hmis = excluded.hmis,
  mode = excluded.mode,
  hazmat = excluded.hazmat,
  taxable = excluded.taxable,
  price = excluded.price,
  sort = excluded.sort;

delete from public.products where sku not in ('cr','cr2','hcr','hcr-t16','descaler','cr-hd','cr-hd-low-foam','neutral','multiwash','lam3','purgo','alumibrite','torque','sar','watersafe60');
