-- Seed the published industry cards as CMS entries.
-- Idempotent. Apply through a service-role connection.

insert into public.content_entries (type, slug, title, status, locale, payload, seo)
values
  ('industry_sector', 'oil-gas', 'Oil & Gas', 'published', 'en', '{"href":"industries/oil-gas","icon":"ph-gas-can","image":"img/industries/samples/oil-gas.webp","image_h":104,"image_w":168,"summary":"Cut heavy grease and scale from rigs, skids, exchangers, valves, and plant equipment with HMIS 0-0-0 products made for hard industrial work.","image_alt":"Oil and gas worker cleaning an isolated valve manifold and heat exchanger","sort_order":1,"image_label":"View Oil, Gas and Process Plants industry page"}'::jsonb, '{}'::jsonb),
  ('industry_sector', 'marine', 'Marine', 'published', 'en', '{"href":"industries/marine","icon":"ph-anchor","image":"img/industries/samples/marine.webp","image_h":104,"image_w":168,"summary":"Wash salt and road film, cut bilge grease, and brighten aluminum without bringing conventional acids and solvent-heavy cleaners aboard.","image_alt":"Boatyard worker cleaning a yacht hull while the vessel is in a lift","sort_order":2,"image_label":"View Marine industry page"}'::jsonb, '{}'::jsonb),
  ('industry_sector', 'manufacturing', 'Manufacturing', 'published', 'en', '{"href":"industries/manufacturing","icon":"ph-factory","image":"img/industries/samples/manufacturing.webp","image_h":104,"image_w":168,"summary":"Cut heavy grease, oil, rust, and scale from production equipment, floors, and plant systems—then get the line back to work.","image_alt":"Manufacturing worker degreasing heavy production machinery","sort_order":3,"image_label":"View Manufacturing industry page"}'::jsonb, '{}'::jsonb),
  ('industry_sector', 'distribution-cold-storage', 'Distribution / Cold Storage', 'published', 'en', '{"href":"industries/distribution-cold-storage","icon":"ph-warehouse","image":"img/industries/samples/distribution-cold-storage.webp","image_h":104,"image_w":168,"summary":"Three Walmart distribution centers switched to CR HD for equipment, floors, kitchens, drains, and other hard warehouse cleaning jobs.","image_alt":"Cold-storage worker cleaning a refrigerated warehouse floor near a forklift","sort_order":4,"image_label":"View Distribution and Cold Storage industry page"}'::jsonb, '{}'::jsonb),
  ('industry_sector', 'food-beverage', 'Food & Beverage', 'published', 'en', '{"href":"industries/food-beverage","icon":"ph-beer-bottle","image":"img/industries/samples/food-beverage.webp","image_h":104,"image_w":168,"summary":"Remove yeast, protein, fat, beer stone, grease, and drain buildup across brewery, distillery, restaurant, and food-plant cleaning.","image_alt":"Food-processing technician operating a clean-in-place skid beside stainless tanks","sort_order":5,"image_label":"View Food and Beverage industry page"}'::jsonb, '{}'::jsonb),
  ('industry_sector', 'healthcare', 'Healthcare', 'published', 'en', '{"href":"industries/healthcare","icon":"ph-hospital","image":"img/industries/samples/healthcare.webp","image_h":104,"image_w":168,"summary":"Clean and service water systems with patients still in the building—without fume events, evacuations, or closing a wing for routine maintenance.","image_alt":"Healthcare facilities technician descaling a plate heat exchanger in a mechanical room","sort_order":6,"image_label":"View Healthcare industry page"}'::jsonb, '{}'::jsonb),
  ('industry_sector', 'construction', 'Construction', 'published', 'en', '{"href":"industries/construction","icon":"ph-crane","image":"img/industries/samples/construction.webp","image_h":104,"image_w":168,"summary":"Clean concrete, equipment, rust, and job-site grime with HMIS 0-0-0 products that are easier to store and use around the crew.","image_alt":"Workers cleaning concrete pump equipment and a commercial job-site slab","sort_order":7,"image_label":"View Construction industry page"}'::jsonb, '{}'::jsonb),
  ('industry_sector', 'military-government', 'Military / Government', 'published', 'en', '{"href":"industries/military-government","icon":"ph-seal-check","image":"img/industries/samples/military-government.webp","image_h":104,"image_w":168,"summary":"Public fleet, facility, and utility teams can buy through SAM.gov using CAGE 0B2Q3 and NAICS 424690.","image_alt":"Public-sector fleet worker washing a utility truck in a maintenance bay","sort_order":8,"image_label":"View Military and Government industry page"}'::jsonb, '{}'::jsonb),
  ('industry_sector', 'education', 'Education', 'published', 'en', '{"href":"industries/education","icon":"ph-graduation-cap","image":"img/industries/samples/education.webp","image_h":104,"image_w":168,"summary":"Give campus crews one HMIS 0-0-0 line for mechanical rooms, kitchens, restrooms, gyms, and exterior cleaning.","image_alt":"Campus facilities worker cleaning stained exterior steps and walkway","sort_order":9,"image_label":"View Education Facilities industry page"}'::jsonb, '{}'::jsonb),
  ('industry_sector', 'hvac-water', 'HVAC / Water Treatment', 'published', 'en', '{"href":"industries/hvac-water","icon":"ph-wind","image":"img/industries/samples/hvac-water.webp","image_h":104,"image_w":168,"summary":"Remove old scale, protect water systems, and keep towers and heat exchangers running with one simpler VertKleen program.","image_alt":"HVAC technician servicing cooling-tower and heat-exchanger water equipment","sort_order":10,"image_label":"View HVAC and Water Treatment industry page"}'::jsonb, '{}'::jsonb),
  ('industry_sector', 'plumbing', 'Plumbing', 'published', 'en', '{"href":"industries/plumbing","icon":"ph-wrench","image":"img/industries/samples/plumbing.webp","image_h":104,"image_w":168,"summary":"Clear scale and calcium from water lines, heaters, fixtures, and drains without the fumes and handling of hydrochloric acid.","image_alt":"Plumber circulating descaling solution through tankless water heaters","sort_order":11,"image_label":"View Plumbing industry page"}'::jsonb, '{}'::jsonb),
  ('industry_sector', 'data-centers', 'Data Centers', 'published', 'en', '{"href":"industries/data-centers","icon":"ph-hard-drives","image":"img/industries/samples/data-centers.webp","image_h":104,"image_w":168,"summary":"Keep cooling towers clean, heat transfer strong, and Legionella controls on track without turning maintenance into an uptime event.","image_alt":"Data-center technician cleaning water-side cooling equipment beside a server aisle","sort_order":12,"image_label":"View Data Centers industry page"}'::jsonb, '{}'::jsonb),
  ('industry_sector', 'golf-courses', 'Golf Courses', 'published', 'en', '{"href":"industries/golf-courses","icon":"ph-flag","image":"img/industries/samples/golf-courses.webp","image_h":104,"image_w":168,"summary":"Clean mowers, carts, irrigation equipment, locker rooms, hardscape, and outdoor stains with fewer harsh products around the property.","image_alt":"Grounds worker cleaning golf-course mowers and carts on a wash pad","sort_order":13,"image_label":"View Golf Courses and Sports Facilities industry page"}'::jsonb, '{}'::jsonb),
  ('industry_sector', 'solar-panel-cleaning', 'Solar / Panel Cleaning', 'published', 'en', '{"href":"industries/solar-panel-cleaning","icon":"ph-sun","image":"img/industries/samples/solar-panel-cleaning.webp","image_h":104,"image_w":168,"summary":"Remove dust, bird residue, algae, and atmospheric film from solar panels with low-pressure cleaning built for large arrays.","image_alt":"Robotic soft-brush cleaner removing soil from a utility-scale solar array","sort_order":14,"image_label":"View Solar Farms and Panel Cleaning industry page"}'::jsonb, '{}'::jsonb),
  ('industry_sector', 'municipalities-water-utilities', 'Municipalities & Water Utilities', 'published', 'en', '{"href":"industries/municipalities-water-utilities","icon":"ph-buildings","image":"img/industries/samples/municipalities-water-utilities.webp","image_h":104,"image_w":168,"summary":"Meet public-water needs with NSF/ANSI/CAN 60-certified treatment, HMIS 0-0-0 cleaners, and strong acid-replacement proof.","image_alt":"Municipal water utility workers cleaning a removed pump impeller and valve","sort_order":15,"image_label":"View Municipalities and Water Utilities industry page"}'::jsonb, '{}'::jsonb),
  ('industry_sector', 'hotels-property-management', 'Hotels / Property Management', 'published', 'en', '{"href":"industries/hotels-property-management","icon":"ph-buildings","image":"img/industries/samples/hotels-property-management.webp","image_h":104,"image_w":168,"summary":"Handle facades, pools, restrooms, HVAC, outdoor stains, and odor complaints without creating a new guest-facing problem.","image_alt":"Hotel facilities worker cleaning a poolside courtyard with a surface cleaner","sort_order":16,"image_label":"View Hotels, Resorts and Property Management industry page"}'::jsonb, '{}'::jsonb)
on conflict (type, slug, locale) do update
  set title = excluded.title, status = excluded.status, payload = excluded.payload,
      seo = excluded.seo, published_at = coalesce(public.content_entries.published_at, now()), updated_at = now();

update public.content_entries set published_at = coalesce(published_at, now())
  where type = 'industry_sector' and status = 'published';
