// Build the MASEST commerce catalog artifacts from data/catalog.seed.json (source of truth).
//
// Applies the CONTROLLED-LAUNCH policy, then re-emits every dependent file in sync:
//   - data/catalog.seed.json   (normalized in place; read by tools/seed-products.mjs)
//   - supabase/variants_seed.sql  (SQL-editor paste path; checkout reads product_variants)
//   - supabase/seed.sql           (product parents)
//   - data/products.seed.json     (legacy mirror, kept consistent)
//
// Controlled-launch policy (owner-approved 2026-06-17):
//   Buyable  = small packs (1 / 2.5 / 5 gal) of the 11 priced cleaning/degreasing products.
//   Quote-only = glycols + WaterSafe60 + CR2 + SAR (unconfirmed small-pack price / freight),
//               and ALL 55 / 275 gal drums & totes (freight quoted post-order).
// Quote-only variants are active=false so /api/products + checkout never sell them.
//
// Idempotent: re-running produces the same output. Run: node tools/build-catalog.mjs
import { readFile, writeFile } from 'node:fs/promises';

const here = (p) => new URL(`../${p}`, import.meta.url);

// Products that are NOT buyable at launch (mode=quote, all variants forced inactive).
// Everything else with a priced small pack stays buyable.
const QUOTE_ONLY_SLUGS = new Set([
  'pg100', 'pg50', 'eg100', 'eg50', 'egu96', 'eg5050', // glycols — price list lives on programs.html
  'watersafe60', 'cr2', 'sar',                          // small-pack price / freight unconfirmed
]);

const catalog = JSON.parse(await readFile(here('data/catalog.seed.json'), 'utf8'));

// 1) Apply policy ----------------------------------------------------------
for (const p of catalog.products) {
  if (QUOTE_ONLY_SLUGS.has(p.slug)) p.mode = 'quote';
}
for (const v of catalog.product_variants) {
  if (QUOTE_ONLY_SLUGS.has(v.product_slug)) {
    v.active = false;
    v.requires_quote = true;
  }
}

// 2) Guardrail — nothing unfulfillable may be buyable -----------------------
const buyable = catalog.product_variants.filter((v) => v.active && v.retail_price != null);
const badPriced = buyable.filter((v) => !(Number(v.retail_price) > 0));
const bigBuyable = buyable.filter((v) => Number(v.size_gal) >= 55);
const dupV = findDupes(catalog.product_variants.map((v) => v.sku));
const dupP = findDupes(catalog.products.map((p) => p.slug));
const errors = [];
if (badPriced.length) errors.push(`buyable variants with no price: ${badPriced.map((v) => v.sku).join(', ')}`);
if (bigBuyable.length) errors.push(`55/275 gal variants left buyable: ${bigBuyable.map((v) => v.sku).join(', ')}`);
if (dupV.length) errors.push(`duplicate vsku: ${dupV.join(', ')}`);
if (dupP.length) errors.push(`duplicate slug: ${dupP.join(', ')}`);
if (errors.length) {
  console.error('build-catalog guardrail FAILED:\n  - ' + errors.join('\n  - '));
  process.exit(1);
}

// 3) Emit files ------------------------------------------------------------
await writeFile(here('data/catalog.seed.json'), JSON.stringify(catalog, null, 2) + '\n');

await writeFile(here('supabase/variants_seed.sql'), variantsSql(catalog.product_variants));
await writeFile(here('supabase/seed.sql'), productsSql(catalog.products));
await writeFile(here('data/products.seed.json'), productsJson(catalog.products));
await writeFile(here('data/drum-pricing.json'), drumPricingJson(catalog.product_variants));

const buyProducts = catalog.products.filter((p) => p.mode === 'buy').length;
console.log(
  `build-catalog OK — ${catalog.products.length} products (${buyProducts} buy / ${catalog.products.length - buyProducts} quote), ` +
  `${catalog.product_variants.length} variants (${buyable.length} buyable), ${catalog.services.length + catalog.service_packages.length} services/packages.`
);

// --- helpers --------------------------------------------------------------
function findDupes(arr) {
  const seen = new Set(), dupes = new Set();
  for (const x of arr) (seen.has(x) ? dupes : seen).add(x);
  return [...dupes];
}

function sqlNum(v) {
  return v == null ? 'null' : String(Number(v) % 1 === 0 ? Number(v) : v);
}

function variantsSql(variants) {
  const head =
    '-- MASEST product variants — generated by tools/build-catalog.mjs from data/catalog.seed.json. DO NOT edit by hand.\n' +
    '-- active=true  → public checkout may sell the variant (priced small packs only).\n' +
    '-- active=false → quote-only: unpriced, or a 55/275 gal drum/tote with freight quoted post-order.\n' +
    'insert into public.product_variants (vsku, product_sku, label, gallons, price, active, sort) values\n';
  const rows = variants.map((v) =>
    `  ('${v.sku}','${v.product_slug}','${v.label}',${sqlNum(v.size_gal)},${sqlNum(v.retail_price)},${v.active},${v.sort})`
  );
  const tail =
    '\non conflict (vsku) do update set\n' +
    '  product_sku = excluded.product_sku,\n  label = excluded.label,\n  gallons = excluded.gallons,\n' +
    '  price = excluded.price,\n  active = excluded.active,\n  sort = excluded.sort;\n';
  return head + rows.join(',\n') + tail;
}

function productsSql(products) {
  const head =
    '-- MASEST product parents — generated by tools/build-catalog.mjs from data/catalog.seed.json. DO NOT edit by hand.\n' +
    '-- Run AFTER schema.sql, then variants_seed.sql. Prices are null on parents (variant-priced).\n' +
    '-- mode=buy → cart/checkout UI; mode=quote → quote form only.\n' +
    'insert into public.products (sku, name, group_key, hmis, mode, hazmat, taxable, price, sort) values\n';
  const rows = products.map((p) =>
    `  ('${p.slug}', ${sqlStr(p.name)}, '${p.group_key}', '${p.hmis}', '${p.mode}', ${p.hazmat}, ${p.taxable}, null, ${p.sort})`
  );
  const tail =
    '\non conflict (sku) do update set\n' +
    '  name = excluded.name,\n  group_key = excluded.group_key,\n  hmis = excluded.hmis,\n' +
    '  mode = excluded.mode,\n  hazmat = excluded.hazmat,\n  taxable = excluded.taxable,\n  sort = excluded.sort,\n' +
    '  updated_at = now();\n  -- price intentionally NOT updated, so owner-set prices survive a re-run.\n';
  return head + rows.join(',\n') + tail;
}

function productsJson(products) {
  const rows = products.map((p) => ({
    sku: p.slug, name: p.name, group_key: p.group_key, hmis: p.hmis,
    mode: p.mode, hazmat: p.hazmat, taxable: p.taxable, price: null, sort: p.sort,
  }));
  return JSON.stringify(rows, null, 2) + '\n';
}

function sqlStr(s) { return `'${String(s).replace(/'/g, "''")}'`; }

// Slim per-product list of priced 55/275 gal drums & totes for the product-page
// "request a quote" reference block. Display only — never feeds cart/checkout.
function drumPricingJson(variants) {
  const out = {};
  for (const v of variants) {
    if (Number(v.size_gal) >= 55 && v.retail_price != null) {
      (out[v.product_slug] ||= []).push({
        label: v.label, gallons: Number(v.size_gal), price: Number(v.retail_price), currency: v.currency || 'usd',
      });
    }
  }
  for (const slug of Object.keys(out)) out[slug].sort((a, b) => a.gallons - b.gallons);
  return JSON.stringify(out, null, 2) + '\n';
}
