// Build MASEST commerce catalog artifacts from data/catalog.seed.json.
//
// Catalog policy, owner-approved 2026-06-20:
// - Most product families are buyable in small packs: 1, 2.5, and 5 gal.
// - Documentation-gated products stay quote-first until SDS/TDS,
//   certificate-status, and launch pricing proof are confirmed: WaterSafe60,
//   CR2, SAR, EG 50/50.
// - Bulk 55/275 gal drums and totes stay quote-routed because freight/final
//   scope changes at that size.
// - Prices are intentionally absent. Live CMS/database pricing is authoritative.
//
// Idempotent: re-running produces the same output.
// Run: node tools/build-catalog.mjs

import { readFile, writeFile } from 'node:fs/promises';

const here = (p) => new URL(`../${p}`, import.meta.url);

const catalog = JSON.parse(await readFile(here('data/catalog.seed.json'), 'utf8'));

// 1) Apply product and variant policy.
for (const product of catalog.products) {
  product.mode = 'buy';
}

for (const variant of catalog.product_variants) {
  const gallons = Number(variant.size_gal);
  delete variant.currency;
  delete variant.notes;
  delete variant.source;
  if (gallons >= 55) {
    variant.active = false;
    variant.requires_quote = true;
  }
}

// 2) Guardrails.
const activeVariants = catalog.product_variants.filter((v) => v.active);
const bigBuyable = activeVariants.filter((v) => Number(v.size_gal) >= 55);
const dupV = findDupes(catalog.product_variants.map((v) => v.sku));
const dupP = findDupes(catalog.products.map((p) => p.slug));
const errors = [
  ...bigBuyable.map((v) => `bulk variant must be quote-routed: ${v.sku}`),
  ...dupV.map((sku) => `duplicate variant sku: ${sku}`),
  ...dupP.map((slug) => `duplicate product slug: ${slug}`),
];
if (errors.length) {
  console.error('build-catalog failed:\n' + errors.join('\n'));
  process.exit(1);
}

// 3) Emit artifacts.
await writeFile(here('data/catalog.seed.json'), JSON.stringify(catalog, null, 2) + '\n');
await writeFile(here('supabase/variants_seed.sql'), variantsSql(catalog.product_variants));
await writeFile(here('supabase/seed.sql'), productsSql(catalog.products));
await writeFile(here('data/products.seed.json'), productsJson(catalog.products));
await writeFile(here('data/services.json'), servicesJson(catalog));

console.log(`catalog: ${catalog.products.length} products, ${catalog.product_variants.length} variants, ${activeVariants.length} active small-pack variants, ${(catalog.services || []).length + (catalog.service_packages || []).length} services`);

function findDupes(items) {
  const seen = new Set();
  const dupes = new Set();
  for (const item of items) {
    if (seen.has(item)) dupes.add(item);
    seen.add(item);
  }
  return [...dupes];
}

function productsJson(products) {
  const rows = products.map((p) => ({
    sku: p.slug,
    name: p.name,
    group_key: p.group_key,
    hmis: p.hmis,
    mode: p.mode,
    hazmat: p.hazmat,
    taxable: p.taxable,
    sort: p.sort,
  }));
  return JSON.stringify(rows, null, 2) + '\n';
}

function productsSql(products) {
  const currentSkus = products.map((p) => sqlStr(p.slug)).join(',');
  const rows = products.map((p) => `(${[
    sqlStr(p.slug),
    sqlStr(p.name),
    sqlStr(p.group_key),
    sqlStr(p.hmis),
    sqlStr(p.mode),
    Boolean(p.hazmat),
    Boolean(p.taxable),
    Number(p.sort || 0),
  ].join(',')})`);
  return `-- MASEST products - generated by tools/build-catalog.mjs from data/catalog.seed.json. DO NOT edit by hand.\n`
    + `insert into public.products (sku, name, group_key, hmis, mode, hazmat, taxable, sort)\nvalues\n`
    + rows.join(',\n')
    + `\non conflict (sku) do update set\n`
    + `  name = excluded.name,\n`
    + `  group_key = excluded.group_key,\n`
    + `  hmis = excluded.hmis,\n`
    + `  mode = excluded.mode,\n`
    + `  hazmat = excluded.hazmat,\n`
    + `  taxable = excluded.taxable,\n`
    + `  sort = excluded.sort;\n\n`
    + `delete from public.products where sku not in (${currentSkus});\n`;
}

function variantsSql(variants) {
  const currentVskus = variants.map((v) => sqlStr(v.sku)).join(',');
  const rows = variants.map((v) => `(${[
    sqlStr(v.sku),
    sqlStr(v.product_slug),
    sqlStr(v.label),
    Number(v.size_gal),
    Boolean(v.active),
    Number(v.sort || 0),
  ].join(',')})`);
  return `-- MASEST product variants - generated by tools/build-catalog.mjs from data/catalog.seed.json. DO NOT edit by hand.\n`
    + `-- Prices are CMS/database-managed and intentionally omitted.\n`
    + `-- active=true -> public checkout may sell the variant when CMS pricing exists.\n`
    + `-- active=false -> bulk quote route or unavailable checkout variant.\n`
    + `delete from public.product_variants where vsku not in (${currentVskus});\n\n`
    + `insert into public.product_variants (vsku, product_sku, label, gallons, active, sort)\nvalues\n`
    + rows.join(',\n')
    + `\non conflict (vsku) do update set\n`
    + `  product_sku = excluded.product_sku,\n`
    + `  label = excluded.label,\n`
    + `  gallons = excluded.gallons,\n`
    + `  active = excluded.active,\n`
    + `  sort = excluded.sort;\n`;
}

// Public services catalog fetched by js/main/service-catalog.js (services.html + about.html).
// Only client-safe fields — internal `source` / `payment_capture` notes are dropped.
function servicesJson(catalog) {
  const pub = (item) => ({
    sku: item.sku,
    name: item.name,
    summary: item.summary,
    category: item.category,
    unit: item.unit,
    active: item.active !== false,
    ...(item.sort_order != null ? { sort_order: Number(item.sort_order) } : {}),
    ...(item.lifecycle_stage ? { lifecycle_stage: item.lifecycle_stage } : {}),
  });
  return JSON.stringify({
    services: (catalog.services || []).map(pub),
    service_packages: (catalog.service_packages || []).map(pub),
  }, null, 2) + '\n';
}

function sqlStr(value) {
  return `'${String(value ?? '').replace(/'/g, "''")}'`;
}
